"""
HyperSeg Decoder - Primary Network Decoder
Based on: "HyperSeg: Patch-wise Hypernetwork for Real-time Semantic Segmentation"
          Nirkin et al., CVPR 2021
          https://github.com/YuvalNirkin/hyperseg

Architecture:
  - The decoder (d) consists of (n+1) meta blocks: m0, m1, ..., mn
  - m0 corresponds to the input image (stem block)
  - Each mi (i=1..n) corresponds to encoder feature map Fi
  - Each meta block uses dynamically generated weights (from the hypernetwork)
  - Weights vary spatially (per-patch) and per-input
  - Each block is followed by 2x bilinear upsampling + concatenation with the
    next finer encoder feature
  - Skip connections link encoder features to decoder meta blocks
  - Positional embeddings are concatenated with each feature map

Dynamic Patch-wise Convolution:
  - Weights are generated by the weight mapping network (wi) per meta block
  - Each patch of the spatial feature map uses its own local conv weights
  - Implemented as a grouped/locally-connected convolution over patches
"""

import math
import torch
import torch.nn as nn
import torch.nn.functional as F
from typing import List, Optional


# ---------------------------------------------------------------------------
# Positional Embedding
# ---------------------------------------------------------------------------

class PositionalEmbedding(nn.Module):
    """
    Learned 2-D positional embedding that is concatenated with feature maps.
    Produces a (1, embed_dim, H, W) map that is tiled to match any spatial size.
    """

    def __init__(self, embed_dim: int, max_h: int = 128, max_w: int = 128):
        super().__init__()
        self.embed_dim = embed_dim
        self.pe = nn.Parameter(torch.zeros(1, embed_dim, max_h, max_w))
        nn.init.trunc_normal_(self.pe, std=0.02)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Return positional embedding resized to match x's spatial dims."""
        H, W = x.shape[-2], x.shape[-1]
        return F.interpolate(self.pe, size=(H, W), mode='bilinear', align_corners=False)


# ---------------------------------------------------------------------------
# Dynamic Patch-wise Convolution
# ---------------------------------------------------------------------------

class DynamicPatchConv(nn.Module):
    """
    Patch-wise locally-connected convolution whose weights vary spatially.

    The spatial feature map is divided into non-overlapping patches of size
    (patch_h x patch_w).  Each patch receives its own set of conv weights,
    generated externally by the weight mapping network.

    Args:
        in_channels  : input channels per patch
        out_channels : output channels per patch
        kernel_size  : spatial kernel size (square)
        patch_size   : size of each spatial patch (square)
        padding      : same-padding for the kernel
    """

    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        kernel_size: int = 3,
        patch_size: int = 4,
        padding: int = 1,
    ):
        super().__init__()
        self.in_channels = in_channels
        self.out_channels = out_channels
        self.kernel_size = kernel_size
        self.patch_size = patch_size
        self.padding = padding
        self.weight_dim = out_channels * in_channels * kernel_size * kernel_size

    def forward(self, x: torch.Tensor, weights: torch.Tensor) -> torch.Tensor:
        """
        Args:
            x       : (B, C_in, H, W)
            weights : (B, num_patches_h, num_patches_w, weight_dim)
                      where weight_dim = C_out * C_in * K * K
        Returns:
            out     : (B, C_out, H, W)
        """
        B, C_in, H, W = x.shape
        ps = self.patch_size
        nh = H // ps  # number of patches in H
        nw = W // ps  # number of patches in W

        # Pad if not evenly divisible
        pad_h = (ps - H % ps) % ps
        pad_w = (ps - W % ps) % ps
        if pad_h > 0 or pad_w > 0:
            x = F.pad(x, (0, pad_w, 0, pad_h))
        H_pad, W_pad = x.shape[-2], x.shape[-1]
        nh = H_pad // ps
        nw = W_pad // ps

        # Reshape weights: (B, nh, nw, C_out, C_in, K, K)
        K = self.kernel_size
        Co = self.out_channels
        Ci = self.in_channels
        w = weights[:, :nh, :nw, :].contiguous()
        w = w.view(B * nh * nw, Co, Ci, K, K)

        # Extract patches from x → (B*nh*nw, C_in, ps, ps)
        # Use unfold to extract non-overlapping patches
        x_unf = x.unfold(2, ps, ps).unfold(3, ps, ps)
        # x_unf: (B, C_in, nh, nw, ps, ps)
        x_patches = x_unf.permute(0, 2, 3, 1, 4, 5).contiguous()
        x_patches = x_patches.view(B * nh * nw, C_in, ps, ps)

        # Apply per-patch convolution: treat (B*nh*nw) as batch dimension
        # Use grouped conv via a single conv2d over the reshaped batch
        out_patches = F.conv2d(
            x_patches, w.view(B * nh * nw * Co, Ci, K, K),
            padding=self.padding, groups=B * nh * nw
        )
        # Actually use the loop-free grouped trick:
        # reshape to (1, B*nh*nw*C_in, ps, ps) and groups=B*nh*nw
        x_patches_grouped = x_patches.view(1, B * nh * nw * Ci, ps, ps)
        w_grouped = w.view(B * nh * nw * Co, Ci, K, K)
        out_grouped = F.conv2d(
            x_patches_grouped, w_grouped,
            padding=self.padding, groups=B * nh * nw
        )  # (1, B*nh*nw*Co, ps, ps)

        out_patches = out_grouped.view(B, nh, nw, Co, ps, ps)
        # Reassemble patches → (B, Co, H_pad, W_pad)
        out = out_patches.permute(0, 3, 1, 4, 2, 5).contiguous()
        out = out.view(B, Co, H_pad, W_pad)

        # Crop back if padded
        if pad_h > 0 or pad_w > 0:
            out = out[:, :, :H, :W]

        return out


# ---------------------------------------------------------------------------
# Weight Mapping Network (wi) — generates per-patch weights for meta block i
# ---------------------------------------------------------------------------

class WeightMappingNetwork(nn.Module):
    """
    Lightweight MLP that maps context features → patch-wise conv weights
    for a single meta block.

    Operates on the hypernetwork context feature map, downsampled to the
    patch grid resolution.

    Args:
        context_channels : channels in the context feature from the hypernetwork
        weight_dim       : total number of weight values per patch
                           (= C_out * C_in * K * K)
        hidden_dim       : hidden layer width
        patch_size       : spatial patch size (used to pool context to patch grid)
    """

    def __init__(
        self,
        context_channels: int,
        weight_dim: int,
        hidden_dim: int = 64,
        patch_size: int = 4,
    ):
        super().__init__()
        self.patch_size = patch_size
        self.pool = nn.AdaptiveAvgPool2d(1)  # fallback; replaced per-patch below
        self.net = nn.Sequential(
            nn.Conv2d(context_channels, hidden_dim, 1),
            nn.ReLU(inplace=True),
            nn.Conv2d(hidden_dim, weight_dim, 1),
        )

    def forward(self, context: torch.Tensor, target_hw: tuple) -> torch.Tensor:
        """
        Args:
            context   : (B, C_ctx, H_ctx, W_ctx) — hypernetwork context features
            target_hw : (H, W) of the feature map that will be processed
        Returns:
            weights   : (B, nh, nw, weight_dim)
        """
        H, W = target_hw
        ps = self.patch_size
        nh = math.ceil(H / ps)
        nw = math.ceil(W / ps)
        # Resize context to patch grid resolution
        ctx = F.interpolate(context, size=(nh, nw), mode='bilinear', align_corners=False)
        w = self.net(ctx)          # (B, weight_dim, nh, nw)
        w = w.permute(0, 2, 3, 1)  # (B, nh, nw, weight_dim)
        return w


# ---------------------------------------------------------------------------
# Meta Block  (one decoder stage)
# ---------------------------------------------------------------------------

class MetaBlock(nn.Module):
    """
    A single decoder meta block mi.

    Structure (per the paper):
      1. Concatenate input features with positional embedding
      2. Apply dynamic patch-wise convolution (weights from wi)
      3. BatchNorm + ReLU
      4. Optional 1×1 projection to out_channels

    Args:
        in_channels      : input feature channels (after cat with pos_embed)
        out_channels     : output feature channels
        pos_embed_dim    : positional embedding channels
        kernel_size      : kernel for dynamic conv
        patch_size       : patch size for locally-connected conv
        context_channels : channels of hypernetwork context (for weight gen)
        weight_hidden    : hidden dim of weight mapping MLP
    """

    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        pos_embed_dim: int = 8,
        kernel_size: int = 3,
        patch_size: int = 4,
        context_channels: int = 256,
        weight_hidden: int = 64,
    ):
        super().__init__()
        self.pos_embed = PositionalEmbedding(pos_embed_dim)
        conv_in = in_channels + pos_embed_dim
        self.dynamic_conv = DynamicPatchConv(
            in_channels=conv_in,
            out_channels=out_channels,
            kernel_size=kernel_size,
            patch_size=patch_size,
            padding=kernel_size // 2,
        )
        self.weight_net = WeightMappingNetwork(
            context_channels=context_channels,
            weight_dim=self.dynamic_conv.weight_dim,
            hidden_dim=weight_hidden,
            patch_size=patch_size,
        )
        self.bn = nn.BatchNorm2d(out_channels)
        self.act = nn.ReLU(inplace=True)

    def forward(
        self, x: torch.Tensor, context: torch.Tensor
    ) -> torch.Tensor:
        """
        Args:
            x       : (B, C_in, H, W)  — current feature map
            context : (B, C_ctx, Hc, Wc) — hypernetwork context features
        Returns:
            out     : (B, C_out, H, W)
        """
        H, W = x.shape[-2], x.shape[-1]
        # Concatenate positional embedding
        pos = self.pos_embed(x)
        x = torch.cat([x, pos], dim=1)
        # Generate patch-wise weights from context
        weights = self.weight_net(context, (H, W))
        # Apply dynamic patch conv
        out = self.dynamic_conv(x, weights)
        out = self.act(self.bn(out))
        return out


# ---------------------------------------------------------------------------
# HyperSeg Decoder
# ---------------------------------------------------------------------------

class HyperSegDecoder(nn.Module):
    """
    Primary network decoder (d) for HyperSeg.

    Consists of (n+1) meta blocks.  The stem block m0 processes the input
    image; blocks m1..mn each process the corresponding encoder feature Fi
    (coarse → fine order, i.e. Fi from the deepest to the shallowest encoder
    level).

    After each meta block (except the last), the output is:
        - 2× bilinearly upsampled
        - concatenated with the next finer encoder feature

    The final output is passed through a 1×1 conv to produce num_classes
    logits.

    Args:
        encoder_channels : list of encoder feature channel counts, from coarsest
                           to finest, e.g. [512, 256, 128, 64, 32]
        decoder_channels : list of decoder output channels per meta block
                           (must have the same length as encoder_channels)
        img_channels     : number of input image channels (default 3)
        num_classes      : number of segmentation output classes
        pos_embed_dim    : positional embedding dimension
        kernel_size      : kernel size for dynamic conv
        patch_size       : patch size for locally-connected weights
        context_channels : channels in hypernetwork context features
        weight_hidden    : hidden dim of weight mapping MLP
    """

    def __init__(
        self,
        encoder_channels: List[int],
        decoder_channels: List[int],
        img_channels: int = 3,
        num_classes: int = 21,
        pos_embed_dim: int = 8,
        kernel_size: int = 3,
        patch_size: int = 4,
        context_channels: int = 256,
        weight_hidden: int = 64,
    ):
        super().__init__()
        assert len(encoder_channels) == len(decoder_channels), (
            "encoder_channels and decoder_channels must have the same length"
        )
        self.n = len(encoder_channels)  # number of encoder feature levels

        # Stem block (m0): processes input image
        self.stem = MetaBlock(
            in_channels=img_channels,
            out_channels=decoder_channels[-1],  # finest decoder channels
            pos_embed_dim=pos_embed_dim,
            kernel_size=kernel_size,
            patch_size=patch_size,
            context_channels=context_channels,
            weight_hidden=weight_hidden,
        )

        # Meta blocks m1..mn: from coarsest encoder feature to finest
        # encoder_channels[0] = coarsest (deepest), encoder_channels[-1] = finest
        self.meta_blocks = nn.ModuleList()
        for i in range(self.n):
            # Input channels at block i:
            #   - encoder feature channels at level i
            #   + upsampled output from previous decoder block (if not first)
            if i == 0:
                in_ch = encoder_channels[i]
            else:
                in_ch = encoder_channels[i] + decoder_channels[i - 1]

            self.meta_blocks.append(
                MetaBlock(
                    in_channels=in_ch,
                    out_channels=decoder_channels[i],
                    pos_embed_dim=pos_embed_dim,
                    kernel_size=kernel_size,
                    patch_size=patch_size,
                    context_channels=context_channels,
                    weight_hidden=weight_hidden,
                )
            )

        # Final prediction head
        # The stem output (finest) is concatenated with m1 output after upsample
        final_in = decoder_channels[-1] + decoder_channels[-1]
        self.head = nn.Conv2d(final_in, num_classes, kernel_size=1)

    def forward(
        self,
        img: torch.Tensor,
        encoder_features: List[torch.Tensor],
        context: torch.Tensor,
    ) -> torch.Tensor:
        """
        Args:
            img              : (B, 3, H, W)  — input image
            encoder_features : list of (B, Ci, Hi, Wi) from coarsest to finest
            context          : (B, C_ctx, Hc, Wc) — hypernetwork context features

        Returns:
            logits           : (B, num_classes, H, W)
        """
        assert len(encoder_features) == self.n

        # Process encoder features from coarsest to finest (top-down)
        x = None
        for i, (feat, meta_block) in enumerate(
            zip(encoder_features, self.meta_blocks)
        ):
            if i == 0:
                inp = feat
            else:
                # Upsample previous decoder output to match current encoder feature
                x_up = F.interpolate(x, size=feat.shape[-2:], mode='bilinear', align_corners=False)
                inp = torch.cat([feat, x_up], dim=1)
            x = meta_block(inp, context)

        # x is now at the finest encoder feature resolution
        # Upsample to input image resolution
        x_up = F.interpolate(x, size=img.shape[-2:], mode='bilinear', align_corners=False)

        # Stem block processes the input image at full resolution
        stem_out = self.stem(img, context)

        # Concatenate and predict
        out = torch.cat([stem_out, x_up], dim=1)
        logits = self.head(out)
        return logits


# ---------------------------------------------------------------------------
# Convenience factory: HyperSeg-L (EfficientNet-B3 backbone config)
# ---------------------------------------------------------------------------

def hyperseg_l_decoder(num_classes: int = 21) -> HyperSegDecoder:
    """
    HyperSeg-L decoder using EfficientNet-B3 encoder channel sizes.
    Encoder features (coarse→fine): [384, 136, 48, 32, 24]
    """
    return HyperSegDecoder(
        encoder_channels=[384, 136, 48, 32, 24],
        decoder_channels=[128, 64,  32, 16, 16],
        img_channels=3,
        num_classes=num_classes,
        pos_embed_dim=8,
        kernel_size=3,
        patch_size=4,
        context_channels=256,
        weight_hidden=64,
    )


def hyperseg_m_decoder(num_classes: int = 21) -> HyperSegDecoder:
    """
    HyperSeg-M decoder using EfficientNet-B1 encoder channel sizes.
    """
    return HyperSegDecoder(
        encoder_channels=[320, 112, 40, 24, 16],
        decoder_channels=[96,  48,  24, 16, 16],
        img_channels=3,
        num_classes=num_classes,
        pos_embed_dim=8,
        kernel_size=3,
        patch_size=4,
        context_channels=256,
        weight_hidden=64,
    )


# ---------------------------------------------------------------------------
# Quick sanity test
# ---------------------------------------------------------------------------

if __name__ == '__main__':
    torch.manual_seed(0)
    B, H, W = 2, 512, 1024
    num_classes = 19  # Cityscapes

    decoder = hyperseg_l_decoder(num_classes=num_classes)
    decoder.eval()

    img = torch.randn(B, 3, H, W)

    # Simulated encoder features (coarse → fine)
    enc_feats = [
        torch.randn(B, 384, H // 32, W // 32),  # coarsest
        torch.randn(B, 136, H // 16, W // 16),
        torch.randn(B,  48, H //  8, W //  8),
        torch.randn(B,  32, H //  4, W //  4),
        torch.randn(B,  24, H //  2, W //  2),  # finest
    ]

    # Simulated hypernetwork context (from nested U-Net context head)
    context = torch.randn(B, 256, H // 32, W // 32)

    with torch.no_grad():
        logits = decoder(img, enc_feats, context)

    print(f"Input image  : {img.shape}")
    print(f"Context feat : {context.shape}")
    print(f"Output logits: {logits.shape}")
    assert logits.shape == (B, num_classes, H, W), \
        f"Expected ({B}, {num_classes}, {H}, {W}), got {logits.shape}"
    print("✓ Decoder forward pass OK")

    total_params = sum(p.numel() for p in decoder.parameters())
    print(f"Total params : {total_params:,}")